# MCTS config
episodes: 100
simulations: 100
epsilon: 1
epsilon_decay: 0.99
sigma: 2
sigma_decay: 1
c: 1

# Neural Network config
nr_of_anets: 5
rbuf_size: 512
lr: 0.01
activation: relu
optimizer: adam

# Game general config
starting_player: 1

# Hex config
board_size: 4

# Nim config
nr_of_piles: 7

# Debug config
visualize_tree: false

# Topp config
nr_of_topp_games: 25

# Run config
game: hex
train: true
topp: true
topp_ui: true
