# MCTS config
episodes: 100
simulations: 1000 # m
epsilon: 1
epsilon_decay: 1
sigma: 2
sigma_decay: 1
c: 1

# Neural Network config
nr_of_anets: 5
rbuf_size: 512
lr: 0.01
activation: sigmoid # linear, sigmoid, tanh, RELU
optimizer: adam # Adagrad, Stochastic Gradient Descent (SGD), RMSProp, and Adam
hidden_layers: 3
neurons_per_layer: [256, 512, 256] # (512, 256)
plot_accuracy: true
batch_size: 128

# Game general config
starting_player: 1

# Hex config
board_size: 4 # k

# Nim config
nr_of_piles: 7

# Debug config
visualize_tree: false

# Topp config
nr_of_topp_games: 25 # g

# Run config
game: hex
train: true
save: true
topp: true
topp_ui: false
