# MCTS config
nr_of_search_episodes: 10
nr_of_simulations: 10
epsilon: 1
epsilon_decay: 0.99
sigma: 2
sigma_decay: 1
c: 1

# Neural Network config
nr_of_anets: 5
rbuf_size: 512

# Hex config
starting_player: 1
board_size: 4
nr_of_games: 100

# Nim config
nr_of_piles: 7

# Debug config
visualize_tree: false

# Topp config
nr_of_topp_games: 25

# Run config
train: false
topp: true