# MCTS config
nr_of_search_episodes: 10
nr_of_simulations: 100
epsilon: 1
epsilon_decay: 0.99
sigma: 2
sigma_decay: 1
c: 1

# Neural Network config
nr_of_anets: 5
rbuf_size: 512

# Game config
starting_player: 1
board_size: 3
nr_of_games: 500

# Nim config
nr_of_piles: 4

# Debug config
visualize_tree: false