# MCTS config
episodes: 10
simulations: 200 # m
epsilon: 1
epsilon_decay: 0.99
sigma: 2
sigma_decay: 1
c: 1

# Neural Network config
nr_of_anets: 5 # m
rbuf_size: 512
lr: 0.01
activation: relu # linear, sigmoid, tanh, RELU
optimizer: adam # Adagrad, Stochastic Gradient Descent (SGD), RMSProp, and Adam
hidden_layers: 3
neurons_per_layer: [256, 512, 256] # (512, 256)
batch_size: 128
plot_accuracy: false

# Game general config
starting_player: 1

# Hex config
board_size: 4 # k

# Nim config
nr_of_piles: 7

# Debug config
visualize_tree: false

# Topp config
nr_of_topp_games: 25 # g

# Run config
game: hex
train: true
topp: true
train_ui: false
topp_ui: false
