# MCTS config
episodes: 10
simulations: 100 # m
epsilon: 1
epsilon_decay: 0.9999
sigma: 2
sigma_decay: 1
c: 1

# Neural Network config
nr_of_anets: 5 # m
rbuf_size: 512
lr: 0.001
activation: leaky_relu # linear, sigmoid, tanh, relu, leaky_relu, tanh
optimizer: adam # Adagrad, Stochastic Gradient Descent (SGD), RMSProp, and Adam
loss: cross_entropy # mse, cross_entropy, l1
hidden_layers: 3
neurons_per_layer: [256, 512, 256] # (512, 256)
batch_size: 128
plot_accuracy: false

# Game general config
starting_player: 1

# Hex config
board_size: 4 # k

# Nim config
nr_of_piles: 7

# Debug config
visualize_tree: false

# Topp config
nr_of_topp_games: 25 # g

# Run config
game: hex # hex, nim
test_mcts: true
train: false
topp: false
train_ui: false
topp_ui: false
